site_name: BIMserver Wiki WIP

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - tables

theme:
  name: material
  logo: assets/BIMserver_logo.png
  favicon: assets/BIMserver_logo.png
  language: en
  icon:
    repo: fontawesome/brands/github

  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    #- navigation.expand

  palette:
    # Light mode palette
    - scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-5
        name: Switch to dark mode

    # Dark mode palette
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-3
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/opensourceBIM/BIMserver

#SIDEBAR
nav:
  - Home: index.md
  - Get Started:
    - Quick Guide: Get-Started-Quick-Guide.md
    - Requirements:
          - Version 1.2: Requirements-1.2.md
          - Version 1.3: Requirements-1.3.md
          - Version 1.4: Requirements-1.4.md
          - Version 1.4 (2015-09-12): Requirements-1.4---2015-09-12.md
          - Version 1.5: Requirements-1.5.md
    - Download: Download.md
    - JAR Starter: JAR-Starter.md
    - Setup: Setup.md
  
  - Deployment:
    - Ubuntu installation: Install-on-Ubuntu-15.md
    - Windows installation: Tomcat-on-windows.md
    - Security: Security.md
    - Memory Usage: Memory-usage.md
    - More memory: Memory-and-Java.md
    - Performance statistics: Performance-statistics.md
    - Large databases: Large-databases.md

  - Developers:
    - Service Interfaces:
      - Service interfaces: Service-Interfaces.md
      - SOAP: SOAP.md 
      - JSON: JSON-API.md 
      - Protocol Buffers: Protocol-Buffers.md
    - Common Functions:
      - Checkin: Checkin.md 
      - Download: Downloading-models.md
    - Data Model:
      - SProject: Eclipse-setup-with-Team-project-set.md 
      - SRevision: SRevision.md
    - Low Level Calls: Low-Level-Calls.md
    - Endpoints: Endpoints.md

  - Clients:
    - Java Client:
      - Java Client: BimServerClient.md 
      - Java Client (Maven): BimServerClientMavenEclipse.md
    - PHP Client: PHP-Client-Library.md
    - JavaScript Client: JavaScriptClient.md
  
  - BIMServer Developers:
    - Plugins in 1.5: Plugins---new-style.md
    - Plugin Development:
      - Plugin Development: Plugin-Development.md
      - Serializer Plugin:
        - Serializer Plugin: Serializer-Plugin.md 
        - XSLT Serializer: XSLT-Serializer.md 
        - BIMsurfer Serializers: BIMsurfer-Serializers.md 
      - Deserializer Plugin: Deserializer-Plugin.md 
      - Model Compare Plugin: Model-Compare-Plugin.md 
      - Model Merge Plugin: Model-Merge-Plugin.md 
      - Query Engine Plugin: Query-Engine-Plugin.md 
      - Render Engine Plugin: Render-Engine-Plugin.md 
      - ObjectIDM Plugin: ObjectIDM-Plugin.md 
      - Schema Plugin: Schema-Plugin.md 
      - Service Plugin: Service-Plugin.md
    - Eclipse: Eclipse.md
    - Eclipse Modeling Framework: Eclipse-Modeling-Framework.md
    - Embedding: Embedding.md
    - Terminology: Terminology.md
    - Database/Versioning: Database---Versioning.md
    - IFC STEP Encoding: IFC-STEP-Encoding.md
    - Communication: Communication.md
    - Global changes in 1.5: Global-changes-in-1.5.md
    - Writing a service: Writing-a-service,-the-easy-way.md
    - Services/Notifications: Services-Notifications.md
    - BIMserver 1.5 Developers: BIMserver-1.5---Developers.md
    - Extended data: Extended-Data.md
    - Extended data schema: Extended-Data-Schema.md
    - Object IDM: Object-IDMs.md
  
  - New developments:
    - New remote service interface: New-remote-service-interface.md
    - Plugins new: Plugins---New.md
    - Deprecated: Deprecated.md
    - New query language: New-query-langage.md
    - Visual query language:
      - Visual query language: Visual-query-language.md 
      - Contains: Reusable-query-Contains.md 
      - Decomposes: Reusable-query-Decomposes.md 
      - DecomposesContains: Reusable-query-DecomposesContains.md 
      - Properties: Reusable-query-Properties.md 
      - Reusable: Reusable-query-blocks.md
    - Reorganizing BIMserver JavaScript API: Reorganizing-bimserverapi.js.md
  
  - General:
    - FAQ: FAQ.md
    - Issues:
      - Known Issues: Known-issues.md 
      - Problems querying IFC: Problems-with-querying-IFC.md 
      - Web Sockets: Web-socket-error.md
    - License: License.md
    - Feature statusses: Feature-statusses.md
    - Roadmap: Roadmap.md
